spring:
  application:
    name: mlbb-chunky
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mlbb_chunky}
    username: ${DB_USERNAME:chunky}
    password: ${DB_PASSWORD:chunky}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${PORT:8080}
